language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9

install:
  - npm run ci-or-install
os:
  - linux
  - osx
script:
  - npm test
  # make sure when the docs are generated nothing changes (a.k.a. the docs have already been generated)
  - npm run gendocs
  - npm run after-travis "Make sure to generate docs!"
after_success:
  - npm run codecov -- -f coverage/lcov.info

# Gitter
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/743dc6b83b6dd05111ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
