language: c++
sudo: false
env:
  global:
    - secure: B0Kq1xen0S4ot2UwDN1g33TD9JyfwunrEpdihrZurEcPQyBBprl/BC/iNqdnd4oSzP27Q1CxHkSyWMl24DpS3G8gBLbeqI+O5TqpkbhazZ1hLThA5vU/MNXq4XUpmdfKLtotA093teD5D4PKltmcYxcfry62B3AHeHeFUJ5egRY=
    - secure: X+JLi7O6F9Lzgp5aCo9YKzvulIZGw6fmQDVUQ/7Zklc4ZAi0zoOQgtEYuMFnwAMdSmPwjeIjE86NmNYHQp1E6QUArF2m32YDl8IiFzzxjRR7B1kvdz9le3uteghNRDR8Wy0E43e5hm8yEM4obeP+1st6Dzl83YWeb4o18XMUa70=
  matrix:
    - NODE_VERSION="0.10"
    - NODE_VERSION="0.11"
    - NODE_VERSION="0.12"
    - NODE_VERSION="iojs-v1"
    - NODE_VERSION="iojs-v2"
    - NODE_VERSION="iojs-v3"
    - NODE_VERSION="4"
    - NODE_VERSION="5"

matrix:
  allow_failures:
    - NODE_VERSION="0.10"

# keep this blank to make sure there are no before_install steps
before_install:

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm install
os:
  - linux
  - osx
script:
  - npm test
  # make sure when the docs are generated nothing changes (a.k.a. the docs have already been generated)
  - node scripts/generate-docs.js
  - git diff --quiet # make sure no files have changed

# Re-run benchmarks
after_success:
  - |
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        curl -Lo travis_after_all.py https://git.io/travis_after_all
        python travis_after_all.py
        export $(cat .to_export_back) &> /dev/null
        if [ "$BUILD_LEADER" = "YES" ]; then
          if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
            echo "All jobs succeeded! Re-running benchmarks"
            chmod +x travis_build_children.sh
            ./travis_build_children.sh
          else
            echo "Some jobs failed, so won't run benchmarks"
          fi
        fi
      fi

# Gitter
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/743dc6b83b6dd05111ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
